services:
  postgres:
    image: postgres:16
    container_name: smartphone-postgres
    environment:
      POSTGRES_DB: smartphoneshop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: smartphone-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"